INSERT INTO `included` (`id`,  `code`, `name`)
VALUES ('1', 'realestate_included_loggia' , 'Lodja'),
       ('2', 'realestate_included_terrace', 'Terasa'),
       ('3', 'realestate_included_garage', 'Garaza'),
       ('4', 'realestate_included_basement', 'Podrum'),
       ('5', 'realestate_included_pantry', 'Ostava'),
       ('6', 'realestate_included_intercom', 'Interfon'),
       ('7', 'realestate_included_video_surveillance', 'Video nadzor'),
       ('8', 'realestate_included_swimming_pool', 'Bazen'),
       ('9', 'realestate_included_gym', 'Teretana'),
       ('10', 'realestate_included_sauna', 'Sauna'),
       ('11', 'realestate_included_elevator', 'Lift'),
       ('12', 'realestate_included_french_balcony', 'Francuski balkon'),
       ('13', 'realestate_included_parking_spot', 'Parking mesto'),
       ('14', 'realestate_included_hot_water', 'Topla voda'),
       ('15', 'realestate_included_garden', 'Sa bastom'),
       ('16', 'realestate_included_phone', 'Telefon'),
       ('17', 'realestate_included_katv', 'KATV'),
       ('18', 'realestate_included_air_conditioning', 'Klima'),
       ('19', 'realestate_included_internet', 'Internet'),
       ('20', 'realestate_included_fireplace', 'Kamin');